[package]
name = "core-sched"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
core-protocol = { path = "../protocol" }
core-provider = { path = "../provider" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
