use crate::model::{Boundary, PathClaim, Person, Registry};
use anyhow::{Context, Result, bail};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::io::Write as _;
use std::path::Path;

pub fn check_generated(root: &Path, registry: &Registry) -> Result<()> {
    // Generated formats change in two phases because pull requests are validated
    // by the generator from the protected base. Land the exact next format in
    // this allowlist first; only a later pull request may switch the writer.
    let ownership_current = ownership_markdown(registry);
    let ownership_next = ownership_markdown_iteron(registry);
    check_one_of(
        &root.join(&registry.generated.ownership),
        &[&ownership_current, &ownership_next],
    )?;
    check_one(
        &root.join(&registry.generated.codeowners),
        &codeowners(registry),
    )?;
    Ok(())
}

pub fn write_generated(root: &Path, registry: &Registry) -> Result<()> {
    write_atomic(
        &root.join(&registry.generated.ownership),
        &ownership_markdown_iteron(registry),
    )?;
    write_atomic(
        &root.join(&registry.generated.codeowners),
        &codeowners(registry),
    )?;
    Ok(())
}

fn check_one(path: &Path, expected: &str) -> Result<()> {
    let actual = std::fs::read_to_string(path)
        .with_context(|| format!("missing generated file {}", path.display()))?;
    if actual != expected {
        bail!(
            "generated file {} drifted; run `cargo run --locked -p iteron-xtask -- boundaries generate`",
            path.display()
        );
    }
    Ok(())
}

fn check_one_of(path: &Path, expected: &[&str]) -> Result<()> {
    let actual = std::fs::read_to_string(path)
        .with_context(|| format!("missing generated file {}", path.display()))?;
    if !expected.contains(&actual.as_str()) {
        bail!(
            "generated file {} drifted; run `cargo run --locked -p iteron-xtask -- boundaries generate`",
            path.display()
        );
    }
    Ok(())
}

fn write_atomic(path: &Path, contents: &str) -> Result<()> {
    let parent = path
        .parent()
        .with_context(|| format!("generated path {} has no parent", path.display()))?;
    std::fs::create_dir_all(parent)?;
    let temporary = parent.join(format!(
        ".{}.tmp-{}",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("generated"),
        std::process::id()
    ));
    let result = (|| -> Result<()> {
        let mut file = std::fs::OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temporary)
            .with_context(|| format!("cannot create {}", temporary.display()))?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()?;
        std::fs::rename(&temporary, path)
            .with_context(|| format!("cannot replace {}", path.display()))?;
        Ok(())
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&temporary);
    }
    result
}

fn ownership_markdown(registry: &Registry) -> String {
    ownership_markdown_with_brand(registry, "Core", "Core")
}

fn ownership_markdown_iteron(registry: &Registry) -> String {
    ownership_markdown_with_brand(registry, "Iteron", "Iteron")
}

fn ownership_markdown_with_brand(registry: &Registry, title: &str, subject: &str) -> String {
    let mut output = String::new();
    writeln!(output, "# {title} ownership registry\n").unwrap();
    writeln!(
        output,
        "<!-- Generated from governance/boundaries.json. Do not edit this file directly. -->\n"
    )
    .unwrap();
    writeln!(
        output,
        "{subject} has one human Owner/Project Lead and a non-fixed number of human maintainers. A maintainer may own one or several boundaries; these rows are responsibility units, not seats. The Owner retains final override authority.\n"
    )
    .unwrap();
    writeln!(output, "## Enforcement state\n").unwrap();
    let owner = person(registry, &registry.enforcement.project_owner);
    writeln!(
        output,
        "- Mode: `{}`\n- Project Owner: {}\n- Source of truth: [`governance/boundaries.json`](governance/boundaries.json)\n",
        registry.enforcement.mode,
        owner.map(person_label).unwrap_or_else(|| "invalid registry".into())
    )
    .unwrap();
    if registry.enforcement.mode == "bootstrap" {
        writeln!(
            output,
            "> Bootstrap is honest pre-enforcement state: boundaries are claimable, but GitHub cannot request accountable code-owner review until the Owner records explicit public identities and switches the registry to `active`.\n"
        )
        .unwrap();
    }

    writeln!(output, "## Primary boundaries\n").unwrap();
    writeln!(
        output,
        "| Boundary | Status | Risk | Primary | Reviewers | Paths |\n| --- | --- | --- | --- | --- | --- |"
    )
    .unwrap();
    for boundary in &registry.boundaries {
        let primary = boundary
            .primary
            .as_deref()
            .and_then(|id| person(registry, id))
            .map(person_label)
            .unwrap_or_else(|| "Open".into());
        let reviewers = people_labels(registry, &boundary.reviewers);
        writeln!(
            output,
            "| `{}` — {} | {} | {} | {} | {} | {} |",
            boundary.id,
            boundary.title,
            boundary.status,
            boundary.risk,
            primary,
            reviewers,
            path_labels(&boundary.paths)
        )
        .unwrap();
    }
    writeln!(output).unwrap();

    writeln!(output, "## Boundary contracts\n").unwrap();
    for boundary in &registry.boundaries {
        writeln!(output, "### `{}` — {}\n", boundary.id, boundary.title).unwrap();
        writeln!(output, "{}\n", boundary.summary).unwrap();
        writeln!(
            output,
            "- Contracts: {}\n- Required checks: {}\n",
            inline_code_or_none(&boundary.contracts),
            inline_code_or_none(&boundary.checks)
        )
        .unwrap();
    }

    writeln!(output, "## Cross-cutting invariant overlays\n").unwrap();
    writeln!(
        output,
        "An overlay adds review responsibility without becoming a second primary path owner.\n"
    )
    .unwrap();
    writeln!(
        output,
        "| Overlay | Status | Independent review | Reviewers | Trigger paths |\n| --- | --- | --- | --- | --- |"
    )
    .unwrap();
    for overlay in &registry.overlays {
        writeln!(
            output,
            "| `{}` — {} | {} | {} | {} | {} |",
            overlay.id,
            overlay.title,
            overlay.status,
            if overlay.requires_independent_review {
                "required"
            } else {
                "advisory"
            },
            people_labels(registry, &overlay.reviewers),
            path_labels(&overlay.paths)
        )
        .unwrap();
    }
    writeln!(output).unwrap();

    writeln!(output, "## Claiming or changing ownership\n").unwrap();
    writeln!(
        output,
        "1. Open an ownership-claim issue naming the boundary, proposed human primary, reviewer or backup, adjacent contracts, and handoff plan.\n2. The Owner confirms the appointment. An agent cannot claim, approve, inherit, or exercise a human boundary.\n3. Update `governance/boundaries.json`, run `cargo run --locked -p iteron-xtask -- boundaries generate`, and submit both generated files.\n4. Run `cargo run --locked -p iteron-xtask -- boundaries check`. Active enforcement requires every critical boundary and independent overlay to be assigned; critical primaries and affected primaries cannot self-review.\n5. A person may claim several coherent boundaries. Maintainer count is never encoded as a quota."
    )
    .unwrap();
    output
}

fn codeowners(registry: &Registry) -> String {
    let mut output = String::new();
    writeln!(
        output,
        "# Generated from governance/boundaries.json. Do not edit directly."
    )
    .unwrap();
    writeln!(
        output,
        "# CODEOWNERS requests eligible reviewers; governance and repository rules decide approval thresholds."
    )
    .unwrap();
    writeln!(output).unwrap();

    let owner_handle = person(registry, &registry.enforcement.project_owner)
        .and_then(|owner| owner.github.as_deref());
    let mut claims = BTreeMap::new();
    for boundary in &registry.boundaries {
        for claim in &boundary.paths {
            claims
                .entry(codeowners_pattern(claim))
                .or_insert_with(|| claim.clone());
        }
    }
    for overlay in &registry.overlays {
        for claim in &overlay.paths {
            claims
                .entry(codeowners_pattern(claim))
                .or_insert_with(|| claim.clone());
        }
    }

    let mut rows: Vec<_> = claims
        .into_iter()
        .map(|(pattern, claim)| {
            let mut handles = BTreeSet::new();
            let mut scopes = BTreeSet::new();
            for boundary in &registry.boundaries {
                if boundary
                    .paths
                    .iter()
                    .any(|owner_claim| claim_contains(owner_claim, &claim))
                {
                    handles.extend(boundary_handles(registry, boundary, owner_handle));
                    scopes.insert(boundary.id.as_str());
                }
            }
            for overlay in &registry.overlays {
                if overlay
                    .paths
                    .iter()
                    .any(|overlay_claim| claim_contains(overlay_claim, &claim))
                {
                    for reviewer in &overlay.reviewers {
                        if let Some(handle) =
                            person(registry, reviewer).and_then(|reviewer| reviewer.github.as_ref())
                        {
                            handles.insert(handle.clone());
                        }
                    }
                    scopes.insert(overlay.id.as_str());
                }
            }
            if handles.is_empty()
                && let Some(owner) = owner_handle
            {
                handles.insert(owner.to_string());
            }
            (claim_order(&claim), pattern, scopes, handles)
        })
        .collect();
    rows.sort_by(|left, right| left.0.cmp(&right.0));

    for (_, pattern, scopes, handles) in rows {
        if handles.is_empty() {
            writeln!(
                output,
                "# OPEN {pattern} ({}; no eligible GitHub owner recorded)",
                scopes.into_iter().collect::<Vec<_>>().join(", ")
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "{pattern} {}",
                handles.into_iter().collect::<Vec<_>>().join(" ")
            )
            .unwrap();
        }
    }
    output
}

fn claim_contains(cover: &PathClaim, target: &PathClaim) -> bool {
    match target.kind.as_str() {
        "file" => crate::validate::claim_matches(cover, &target.path),
        "tree" => {
            cover.kind == "tree"
                && (cover.path == target.path
                    || target.path.starts_with(&format!("{}/", cover.path)))
        }
        _ => false,
    }
}

fn claim_order(claim: &PathClaim) -> (usize, u8, String) {
    (
        claim.path.split('/').count(),
        u8::from(claim.kind == "file"),
        claim.path.clone(),
    )
}

fn boundary_handles(
    registry: &Registry,
    boundary: &Boundary,
    owner_fallback: Option<&str>,
) -> Vec<String> {
    let ids: Vec<&str> = if boundary.status == "active" {
        boundary
            .primary
            .iter()
            .map(String::as_str)
            .chain(boundary.reviewers.iter().map(String::as_str))
            .collect()
    } else {
        Vec::new()
    };
    let mut handles = BTreeSet::new();
    for id in ids {
        if let Some(handle) = person(registry, id).and_then(|person| person.github.as_ref()) {
            handles.insert(handle.clone());
        }
    }
    if handles.is_empty()
        && let Some(owner) = owner_fallback
    {
        handles.insert(owner.to_string());
    }
    handles.into_iter().collect()
}

fn person<'a>(registry: &'a Registry, id: &str) -> Option<&'a Person> {
    registry.people.iter().find(|person| person.id == id)
}

fn person_label(person: &Person) -> String {
    match &person.github {
        Some(handle) => format!("{} (`{handle}`)", person.display),
        None => person.display.clone(),
    }
}

fn people_labels(registry: &Registry, ids: &[String]) -> String {
    if ids.is_empty() {
        return "Open".into();
    }
    ids.iter()
        .filter_map(|id| person(registry, id))
        .map(person_label)
        .collect::<Vec<_>>()
        .join("<br>")
}

fn path_labels(paths: &[PathClaim]) -> String {
    paths
        .iter()
        .map(|claim| {
            if claim.kind == "tree" {
                format!("`{}/**`", claim.path)
            } else {
                format!("`{}`", claim.path)
            }
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

fn inline_code_or_none(values: &[String]) -> String {
    if values.is_empty() {
        "none".into()
    } else {
        values
            .iter()
            .map(|value| format!("`{value}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn codeowners_pattern(claim: &PathClaim) -> String {
    if claim.kind == "tree" {
        format!("/{}/**", claim.path)
    } else {
        format!("/{}", claim.path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn codeowners_paths_are_rooted_and_tree_aware() {
        assert_eq!(
            codeowners_pattern(&PathClaim {
                kind: "tree".into(),
                path: "crates/kernel".into(),
            }),
            "/crates/kernel/**"
        );
        assert_eq!(
            codeowners_pattern(&PathClaim {
                kind: "file".into(),
                path: "Cargo.toml".into(),
            }),
            "/Cargo.toml"
        );
    }

    #[test]
    fn broader_claims_precede_specific_exceptions() {
        let root = PathClaim {
            kind: "tree".into(),
            path: "crates/provider".into(),
        };
        let file = PathClaim {
            kind: "file".into(),
            path: "crates/provider/src/openai.rs".into(),
        };
        assert!(claim_contains(&root, &file));
        assert!(!claim_contains(&file, &root));
        assert!(claim_order(&root) < claim_order(&file));
    }

    #[test]
    fn bootstrap_owner_is_the_fallback_for_every_codeowners_pattern() {
        let mut registry: Registry =
            serde_json::from_str(include_str!("../../governance/boundaries.json")).unwrap();
        registry.people[0].github = Some("@core-owner".into());
        let generated = codeowners(&registry);
        assert!(!generated.contains("# OPEN "));
        assert!(generated.lines().any(|line| {
            line.starts_with("/crates/agents/** ") && line.ends_with("@core-owner")
        }));
    }

    #[test]
    fn ownership_brand_migration_has_two_exact_formats() {
        let registry: Registry =
            serde_json::from_str(include_str!("../../governance/boundaries.json")).unwrap();
        let current = ownership_markdown(&registry);
        let next = ownership_markdown_iteron(&registry);

        assert!(current.starts_with("# Core ownership registry\n"));
        assert!(next.starts_with("# Iteron ownership registry\n"));
        assert_ne!(current, next);
        assert_eq!(
            current.replacen("# Core", "# Iteron", 1).replacen(
                "Core has one human",
                "Iteron has one human",
                1
            ),
            next
        );
    }
}
