//! Offline projection for the non-authoritative `core-tunables` registry.
//!
//! This module may validate and render metadata only. It has no path to CLI configuration or the
//! runtime, so generation cannot activate a family or change an effective value.

use anyhow::{Context, Result, bail};
use core_tunables::{
    Availability, BenchmarkImpact, DefaultKind, Domain, Family, SourceKind, Trainability,
    ValueKind, canonical_artifact_json, families, registry_digest, validate_registry,
};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

const MACHINE_DOC: &str = "docs/reference/tunables.json";
const HUMAN_DOC: &str = "docs/reference/tunables.md";

pub fn check(root: &Path) -> Result<()> {
    validate_registry().context("invalid built-in tunables registry")?;
    validate_source_locators(root)?;
    check_file(root, MACHINE_DOC, &canonical_artifact_json()?)?;
    check_file(root, HUMAN_DOC, render_markdown()?.as_bytes())?;
    Ok(())
}

pub fn generate(root: &Path) -> Result<()> {
    validate_registry().context("invalid built-in tunables registry")?;
    validate_source_locators(root)?;
    write_file(root, MACHINE_DOC, &canonical_artifact_json()?)?;
    write_file(root, HUMAN_DOC, render_markdown()?.as_bytes())?;
    Ok(())
}

fn validate_source_locators(root: &Path) -> Result<()> {
    for family in families() {
        let locator = family.source.locator;
        if locator.starts_with("crates/") && !root.join(locator).exists() {
            bail!(
                "family `{}` points at missing source locator `{locator}`",
                family.id
            );
        }
    }
    Ok(())
}

fn check_file(root: &Path, relative: &str, expected: &[u8]) -> Result<()> {
    let path = root.join(relative);
    let actual =
        std::fs::read(&path).with_context(|| format!("missing generated {}", path.display()))?;
    if actual != expected {
        bail!(
            "generated file {} drifted; run `cargo run --locked -p core-xtask -- tunables generate`",
            path.display()
        );
    }
    Ok(())
}

fn write_file(root: &Path, relative: &str, bytes: &[u8]) -> Result<()> {
    let path = root.join(relative);
    std::fs::write(&path, bytes).with_context(|| format!("cannot write {}", path.display()))
}

fn render_markdown() -> Result<String> {
    let digest = registry_digest()?;
    let registry = families();
    let mut domains: BTreeMap<Domain, usize> = BTreeMap::new();
    let mut availabilities: BTreeMap<Availability, usize> = BTreeMap::new();
    let mut value_kinds: BTreeMap<ValueKind, usize> = BTreeMap::new();
    for family in registry {
        *domains.entry(family.domain).or_default() += 1;
        *availabilities.entry(family.availability).or_default() += 1;
        *value_kinds.entry(family.value_schema.kind).or_default() += 1;
    }

    let mut out = String::new();
    writeln!(out, "# Tunable-family registry\n")?;
    writeln!(
        out,
        "<!-- Generated by `cargo run --locked -p core-xtask -- tunables generate`. Do not edit directly. -->\n"
    )?;
    writeln!(
        out,
        "This is the versioned, non-authoritative semantic registry for Core tuning analysis. It describes **{}** stable families; it does not change runtime configuration or grant training authority.\n",
        registry.len()
    )?;
    writeln!(
        out,
        "Each `value_schema` supplies a serialized value kind, admissible representation, resolver constraint, and unit. Availability is explicit: `active` means an independently consumed production control, `partial` means a staged, grouped, or incompletely wired seam, and `declared` means no current runtime seam.\n"
    )?;
    writeln!(out, "- Schema: `core-tunables/v1`")?;
    writeln!(
        out,
        "- Canonical digest: `{}:{}`",
        digest.algorithm, digest.value
    )?;
    writeln!(
        out,
        "- Machine artifact: [`tunables.json`](tunables.json)\n"
    )?;
    writeln!(out, "## Domain counts\n")?;
    writeln!(out, "| Domain | Families |")?;
    writeln!(out, "|---|---:|")?;
    for (domain, count) in domains {
        writeln!(out, "| `{}` | {} |", domain_name(domain), count)?;
    }
    writeln!(out, "\n## Availability counts\n")?;
    writeln!(out, "| Availability | Families |")?;
    writeln!(out, "|---|---:|")?;
    for (availability, count) in availabilities {
        writeln!(out, "| `{}` | {} |", availability_name(availability), count)?;
    }
    writeln!(out, "\n## Value-kind counts\n")?;
    writeln!(out, "| Value kind | Families |")?;
    writeln!(out, "|---|---:|")?;
    for (kind, count) in value_kinds {
        writeln!(out, "| `{}` | {} |", value_kind_name(kind), count)?;
    }
    writeln!(out, "\n## Families\n")?;
    writeln!(
        out,
        "| # | Stable ID | Subsystem domain | Value schema | Default | Source | TB 2.1 | SWE-bench Pro | Trainability | Availability |"
    )?;
    writeln!(out, "|---:|---|---|---|---|---|---|---|---|---|")?;
    for family in registry {
        render_family(&mut out, family)?;
    }
    writeln!(out, "\n## Authority boundary\n")?;
    writeln!(
        out,
        "`trainability` is an upper bound on who may propose a value. Runtime admission, operator ceilings, permissions, durability, replay, security, and effect-ledger invariants remain authoritative outside this registry. Benchmark relevance is causal classification, not a score claim."
    )?;
    Ok(out)
}

fn render_family(out: &mut String, family: &Family) -> Result<()> {
    writeln!(
        out,
        "| {} | `{}` | `{}` | `{}`: {}; constraint: {}; unit: {} | `{}`: {} | `{}`: `{}` | `{}` | `{}` | `{}` | `{}` |",
        family.ordinal,
        family.id,
        domain_name(family.domain),
        value_kind_name(family.value_schema.kind),
        escape_cell(family.value_schema.admissible),
        escape_cell(family.value_schema.constraint),
        escape_cell(family.value_schema.unit),
        default_name(family.default.kind),
        escape_cell(family.default.value),
        source_name(family.source.kind),
        escape_cell(family.source.locator),
        impact_name(family.benchmark.terminal_bench_2_1),
        impact_name(family.benchmark.swe_bench_pro),
        trainability_name(family.trainability),
        availability_name(family.availability),
    )?;
    Ok(())
}

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn domain_name(value: Domain) -> &'static str {
    match value {
        Domain::Provider => "provider",
        Domain::Reasoning => "reasoning",
        Domain::Budget => "budget",
        Domain::Context => "context",
        Domain::Memory => "memory",
        Domain::Tooling => "tooling",
        Domain::Verification => "verification",
        Domain::Orchestration => "orchestration",
        Domain::Runtime => "runtime",
        Domain::Extensibility => "extensibility",
        Domain::Observability => "observability",
        Domain::Interface => "interface",
        Domain::Evaluation => "evaluation",
        Domain::Governance => "governance",
    }
}

fn default_name(value: DefaultKind) -> &'static str {
    match value {
        DefaultKind::Literal => "literal",
        DefaultKind::Derived => "derived",
        DefaultKind::Catalog => "catalog",
        DefaultKind::OperatorRequired => "operator_required",
        DefaultKind::Inactive => "inactive",
    }
}

fn source_name(value: SourceKind) -> &'static str {
    match value {
        SourceKind::Cli => "cli",
        SourceKind::UserConfig => "user_config",
        SourceKind::ProjectConfig => "project_config",
        SourceKind::Environment => "environment",
        SourceKind::Builtin => "builtin",
        SourceKind::DerivedPolicy => "derived_policy",
        SourceKind::Catalog => "catalog",
        SourceKind::RuntimeObservation => "runtime_observation",
        SourceKind::ExternalProvider => "external_provider",
        SourceKind::GovernedBundle => "governed_bundle",
        SourceKind::Registry => "registry",
    }
}

fn availability_name(value: Availability) -> &'static str {
    match value {
        Availability::Active => "active",
        Availability::Partial => "partial",
        Availability::Declared => "declared",
    }
}

fn value_kind_name(value: ValueKind) -> &'static str {
    match value {
        ValueKind::Bool => "bool",
        ValueKind::Enum => "enum",
        ValueKind::Count => "count",
        ValueKind::Duration => "duration",
        ValueKind::Bytes => "bytes",
        ValueKind::Ratio => "ratio",
        ValueKind::Decimal => "decimal",
        ValueKind::String => "string",
        ValueKind::List => "list",
        ValueKind::Map => "map",
        ValueKind::Policy => "policy",
        ValueKind::Catalog => "catalog",
    }
}

fn impact_name(value: BenchmarkImpact) -> &'static str {
    match value {
        BenchmarkImpact::None => "none",
        BenchmarkImpact::Conditional => "conditional",
        BenchmarkImpact::Indirect => "indirect",
        BenchmarkImpact::Direct => "direct",
    }
}

fn trainability_name(value: Trainability) -> &'static str {
    match value {
        Trainability::FixedInvariant => "fixed_invariant",
        Trainability::OperatorOnly => "operator_only",
        Trainability::OfflineSearch => "offline_search",
        Trainability::RuntimeAdaptive => "runtime_adaptive",
        Trainability::CatalogCurated => "catalog_curated",
        Trainability::Inactive => "inactive",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask lives below the repository root")
            .to_path_buf()
    }

    #[test]
    fn generated_tunables_artifacts_do_not_drift() {
        check(&root()).expect(
            "tunables docs drifted; run `cargo run --locked -p core-xtask -- tunables generate`",
        );
    }

    #[test]
    fn human_projection_is_non_vacuous_and_names_the_authority_boundary() {
        let rendered = render_markdown().unwrap();
        assert!(rendered.contains("**160** stable families"));
        assert!(rendered.contains("## Value-kind counts"));
        assert!(rendered.contains("`duration`: positive integer milliseconds"));
        assert!(rendered.contains("## Authority boundary"));
        assert!(rendered.contains("`shell_timeout_output`"));
    }

    #[test]
    fn repository_source_locators_are_live() {
        validate_source_locators(&root()).unwrap();
    }
}
