//! Offline projection for the non-authoritative `iteron-tunables` registry and pure resolver contract.
//!
//! This module may validate and render metadata only. It has no path to CLI configuration or the
//! runtime, so generation cannot activate a family or change an effective value.

use anyhow::{Context, Result, bail};
use iteron_tunables::{
    CapabilityRequirement, CoreStrategySlot, DefaultKind, DefaultResolver, Domain, Family,
    FieldDomain, ImplementationStatus, OptimizationClass, ProviderRequirement, REGISTRY_REVISION,
    REGISTRY_SCHEMA_VERSION, RESOLUTION_SCHEMA_VERSION, RelevanceLevel, ScalarDomain, SourceKind,
    SourceTrust, StructuredValueDomain, ValueKind, canonical_artifact_json, families,
    registry_digest, validate_registry,
};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

const MACHINE_DOC: &str = "docs/reference/tunables.json";
const HUMAN_DOC: &str = "docs/reference/tunables.md";

pub fn check(root: &Path) -> Result<()> {
    validate_registry().context("invalid built-in tunables registry")?;
    validate_source_locators(root)?;
    check_file(root, MACHINE_DOC, &canonical_artifact_json()?)?;
    check_file(root, HUMAN_DOC, render_markdown()?.as_bytes())?;
    Ok(())
}

pub fn generate(root: &Path) -> Result<()> {
    validate_registry().context("invalid built-in tunables registry")?;
    validate_source_locators(root)?;
    write_file(root, MACHINE_DOC, &canonical_artifact_json()?)?;
    write_file(root, HUMAN_DOC, render_markdown()?.as_bytes())?;
    Ok(())
}

fn validate_source_locators(root: &Path) -> Result<()> {
    for family in families() {
        for binding in family.source.bindings {
            let locator = binding.locator;
            if locator.starts_with("crates/") && !root.join(locator).exists() {
                bail!(
                    "family `{}` points at missing source locator `{locator}`",
                    family.id
                );
            }
        }
    }
    Ok(())
}

fn check_file(root: &Path, relative: &str, expected: &[u8]) -> Result<()> {
    let path = root.join(relative);
    let actual =
        std::fs::read(&path).with_context(|| format!("missing generated {}", path.display()))?;
    if actual != expected {
        bail!(
            "generated file {} drifted; run `cargo run --locked -p iteron-xtask -- tunables generate`",
            path.display()
        );
    }
    Ok(())
}

fn write_file(root: &Path, relative: &str, bytes: &[u8]) -> Result<()> {
    let path = root.join(relative);
    std::fs::write(&path, bytes).with_context(|| format!("cannot write {}", path.display()))
}

fn render_markdown() -> Result<String> {
    let digest = registry_digest()?;
    let registry = families();
    let mut domains: BTreeMap<Domain, usize> = BTreeMap::new();
    let mut statuses: BTreeMap<ImplementationStatus, usize> = BTreeMap::new();
    let mut value_kinds: BTreeMap<ValueKind, usize> = BTreeMap::new();
    let mut optimization: BTreeMap<OptimizationClass, usize> = BTreeMap::new();
    for family in registry {
        *domains.entry(family.domain).or_default() += 1;
        *statuses.entry(family.implementation_status).or_default() += 1;
        *value_kinds.entry(family.value_schema.kind).or_default() += 1;
        *optimization.entry(family.optimization.class).or_default() += 1;
    }

    let mut out = String::new();
    writeln!(out, "# Tunable registry and pure resolver\n")?;
    writeln!(
        out,
        "<!-- Generated by `cargo run --locked -p iteron-xtask -- tunables generate`. Do not edit directly. -->\n"
    )?;
    writeln!(
        out,
        "This is the versioned semantic registry and contract source for Core's deterministic provider-free resolver. It describes **{}** stable families. The resolver consumes only an explicit frozen input and returns a simulation: neither this artifact nor a resolved set reads or changes runtime configuration, grants authority, or makes a parameter trainable. The runtime remains the sole admission authority.\n",
        registry.len()
    )?;
    writeln!(
        out,
        "Every entry carries a canonical runtime-control semantic key, aliases, a structured activation predicate and inactive reason, provider/capability requirements, one or more of the nine core StrategySlot bindings, exact source provenance, implementation status, a tagged and bounded value domain, source-controlled external-constraint projection/relation/action, formal SWE-bench Pro then Terminal-Bench 2.1 relevance, optimization/search phase, risk, authority, schema version, and an independent SHA-256 family digest in the machine artifact. Semantic keys—not family digests—enforce single ownership of runtime controls. Invalid, unattested, unresolved, or rejected active entries fail atomically; explanation output is bounded and redacted.\n"
    )?;
    writeln!(
        out,
        "- Registry schema: `iteron-tunables/v{REGISTRY_SCHEMA_VERSION}` (revision `{REGISTRY_REVISION}`)"
    )?;
    writeln!(
        out,
        "- Pure resolution input schema: `iteron-tunables-resolution/v{RESOLUTION_SCHEMA_VERSION}`"
    )?;
    writeln!(
        out,
        "- Canonical digest: `{}:{}`",
        digest.algorithm, digest.value
    )?;
    writeln!(
        out,
        "- Machine artifact: [`tunables.json`](tunables.json)\n"
    )?;
    render_counts(&mut out, "Domain", domains, domain_name)?;
    render_counts(
        &mut out,
        "Implementation status",
        statuses,
        implementation_status_name,
    )?;
    render_counts(&mut out, "Value kind", value_kinds, value_kind_name)?;
    render_counts(
        &mut out,
        "Optimization class",
        optimization,
        optimization_name,
    )?;

    writeln!(out, "\n## Families\n")?;
    writeln!(
        out,
        "| # | Stable ID | Semantic key | Domain | Structured value domain | Default | Source / trust / locator | Requirements | SWE | TB 2.1 | Optimization | Status | StrategySlot |"
    )?;
    writeln!(
        out,
        "|---:|---|---|---|---|---|---|---|---|---|---|---|---|"
    )?;
    for family in registry {
        render_family(&mut out, family)?;
    }
    writeln!(out, "\n## Authority boundary\n")?;
    writeln!(
        out,
        "`optimization.class` is an upper bound on candidate production, not evidence that a live trainer or resolver is wired. `pin` entries remain outside search. Runtime admission, operator ceilings, permissions, durability, replay, security, and effect-ledger invariants remain authoritative outside this registry. Formal benchmark relevance is `high`, `medium`, or `low`; the separately serialized causal path and this registry do not promise a score delta."
    )?;
    Ok(out)
}

fn render_counts<K: Ord + Copy>(
    out: &mut String,
    heading: &str,
    counts: BTreeMap<K, usize>,
    name: fn(K) -> &'static str,
) -> Result<()> {
    writeln!(out, "\n## {heading} counts\n")?;
    writeln!(out, "| {heading} | Families |")?;
    writeln!(out, "|---|---:|")?;
    for (value, count) in counts {
        writeln!(out, "| `{}` | {} |", name(value), count)?;
    }
    Ok(())
}

fn render_family(out: &mut String, family: &Family) -> Result<()> {
    let slots = family
        .strategy_slots
        .iter()
        .copied()
        .map(slot_name)
        .collect::<Vec<_>>()
        .join(", ");
    let sources = family
        .source
        .bindings
        .iter()
        .map(|binding| {
            format!(
                "{}/{} ({})",
                source_name(binding.kind),
                source_trust_name(binding.trust),
                binding.locator
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let capabilities = family
        .requirements
        .capabilities
        .iter()
        .copied()
        .map(capability_name)
        .collect::<Vec<_>>()
        .join(", ");
    let requirements = format!(
        "provider={}; {}",
        provider_requirement_name(family.requirements.provider),
        capabilities
    );
    let default = match family.default.value {
        Some(value) => serde_json::to_string(&value)?,
        None => resolver_name(family.default.resolver),
    };
    writeln!(
        out,
        "| {} | `{}` | `{}` | `{}` | {} | `{}`: {} | {} | {} | `{}` | `{}` | `{}` | `{}` | {} |",
        family.ordinal,
        family.id,
        family.semantic_key,
        domain_name(family.domain),
        escape_cell(&value_domain_summary(family.value_schema.domain)),
        default_name(family.default.kind),
        escape_cell(&default),
        escape_cell(&sources),
        escape_cell(&requirements),
        relevance_name(family.benchmark_relevance.swe_bench_pro),
        relevance_name(family.benchmark_relevance.terminal_bench_2_1),
        optimization_name(family.optimization.class),
        implementation_status_name(family.implementation_status),
        slots
            .split(", ")
            .map(|slot| format!("`{slot}`"))
            .collect::<Vec<_>>()
            .join(", "),
    )?;
    Ok(())
}

fn value_domain_summary(domain: StructuredValueDomain) -> String {
    match domain {
        StructuredValueDomain::Scalar { domain } => scalar_domain_summary(domain),
        StructuredValueDomain::List {
            min_items,
            max_items,
            item,
            ..
        } => format!(
            "list items [{}..{}], {}",
            min_items,
            max_items,
            scalar_domain_summary(item)
        ),
        StructuredValueDomain::Map {
            min_entries,
            max_entries,
            key,
            value,
            ..
        } => format!(
            "map entries [{}..{}], key={}, value={}",
            min_entries,
            max_entries,
            scalar_domain_summary(key),
            field_domain_summary(value)
        ),
        StructuredValueDomain::Object { fields, .. } => format!(
            "closed object ({} fields, {} required)",
            fields.len(),
            fields.iter().filter(|field| field.required).count()
        ),
        StructuredValueDomain::Catalog {
            catalog_id,
            min_entries,
            max_entries,
            entry_fields,
        } => format!(
            "catalog {catalog_id}, entries [{}..{}], {} typed fields",
            min_entries,
            max_entries,
            entry_fields.len()
        ),
    }
}

fn scalar_domain_summary(domain: ScalarDomain) -> String {
    match domain {
        ScalarDomain::Boolean => "boolean".into(),
        ScalarDomain::Integer { min, max, unit } => {
            format!("integer [{min}..{max}] {unit}")
        }
        ScalarDomain::Decimal {
            min,
            max,
            max_scale,
            unit,
        } => format!(
            "decimal [{}e-{}..{}e-{}] {unit}, scale<={max_scale}",
            min.coefficient, min.scale, max.coefficient, max.scale
        ),
        ScalarDomain::Text {
            min_bytes,
            max_bytes,
            format,
        } => format!("text bytes [{min_bytes}..{max_bytes}], {format:?}"),
        ScalarDomain::Enum { values, catalog_id } => catalog_id.map_or_else(
            || format!("enum [{}]", values.join(", ")),
            |catalog| format!("catalog enum {catalog}"),
        ),
    }
}

fn field_domain_summary(domain: FieldDomain) -> String {
    match domain {
        FieldDomain::Scalar { domain } => scalar_domain_summary(domain),
        FieldDomain::List {
            min_items,
            max_items,
            item,
            ..
        } => format!(
            "list [{min_items}..{max_items}] of {}",
            scalar_domain_summary(item)
        ),
        FieldDomain::Map {
            min_entries,
            max_entries,
            key,
            value,
        } => format!(
            "map [{min_entries}..{max_entries}] {} -> {}",
            scalar_domain_summary(key),
            scalar_domain_summary(value)
        ),
        FieldDomain::Object { fields, .. } => format!("closed object ({} fields)", fields.len()),
    }
}

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn domain_name(value: Domain) -> &'static str {
    match value {
        Domain::Provider => "provider",
        Domain::Reasoning => "reasoning",
        Domain::Budget => "budget",
        Domain::Context => "context",
        Domain::Memory => "memory",
        Domain::Tooling => "tooling",
        Domain::Verification => "verification",
        Domain::Orchestration => "orchestration",
        Domain::Runtime => "runtime",
        Domain::Extensibility => "extensibility",
        Domain::Observability => "observability",
        Domain::Interface => "interface",
        Domain::Evaluation => "evaluation",
        Domain::Governance => "governance",
    }
}

fn default_name(value: DefaultKind) -> &'static str {
    match value {
        DefaultKind::Literal => "literal",
        DefaultKind::Derived => "derived",
        DefaultKind::Dynamic => "dynamic",
    }
}

fn resolver_name(value: DefaultResolver) -> String {
    match value {
        DefaultResolver::Literal => "literal".into(),
        DefaultResolver::Builtin { resolver_id } => format!("builtin:{resolver_id}"),
        DefaultResolver::ModelMetadata { field } => format!("model_metadata:{field}"),
        DefaultResolver::ProviderCapability { capability } => {
            format!("provider_capability:{capability}")
        }
        DefaultResolver::Transport { field } => format!("transport:{field}"),
        DefaultResolver::RuntimeObservation { field } => {
            format!("runtime_observation:{field}")
        }
        DefaultResolver::GovernedCatalog { catalog_id } => {
            format!("governed_catalog:{catalog_id}")
        }
        DefaultResolver::Operator { input_id } => format!("operator:{input_id}"),
    }
}

fn provider_requirement_name(value: ProviderRequirement) -> &'static str {
    match value {
        ProviderRequirement::None => "none",
        ProviderRequirement::AnyAdmittedRoute => "any_admitted_route",
        ProviderRequirement::SelectedRoute => "selected_route",
    }
}

fn capability_name(value: CapabilityRequirement) -> String {
    serde_json::to_string(&value)
        .expect("serializing a fieldless capability enum cannot fail")
        .trim_matches('"')
        .to_owned()
}

fn source_name(value: SourceKind) -> &'static str {
    match value {
        SourceKind::Cli => "cli",
        SourceKind::OperatorInput => "operator_input",
        SourceKind::RustBuilder => "rust_builder",
        SourceKind::UserConfig => "user_config",
        SourceKind::ProjectConfig => "project_config",
        SourceKind::Environment => "environment",
        SourceKind::Builtin => "builtin",
        SourceKind::DerivedPolicy => "derived_policy",
        SourceKind::Catalog => "catalog",
        SourceKind::RuntimeObservation => "runtime_observation",
        SourceKind::ExternalProvider => "external_provider",
        SourceKind::GovernedBundle => "governed_bundle",
        SourceKind::Registry => "registry",
    }
}

fn source_trust_name(value: SourceTrust) -> &'static str {
    match value {
        SourceTrust::Operator => "operator",
        SourceTrust::Repository => "repository",
        SourceTrust::Builtin => "builtin",
        SourceTrust::RuntimeObservation => "runtime_observation",
        SourceTrust::ProviderAttested => "provider_attested",
        SourceTrust::GovernedBundle => "governed_bundle",
        SourceTrust::RegistryDeclaration => "registry_declaration",
    }
}

fn implementation_status_name(value: ImplementationStatus) -> &'static str {
    match value {
        ImplementationStatus::Full => "full",
        ImplementationStatus::Partial => "partial",
        ImplementationStatus::Missing => "missing",
        ImplementationStatus::FixedHidden => "fixed_hidden",
    }
}

fn value_kind_name(value: ValueKind) -> &'static str {
    match value {
        ValueKind::Bool => "bool",
        ValueKind::Enum => "enum",
        ValueKind::Count => "count",
        ValueKind::Duration => "duration",
        ValueKind::Bytes => "bytes",
        ValueKind::Ratio => "ratio",
        ValueKind::Decimal => "decimal",
        ValueKind::String => "string",
        ValueKind::List => "list",
        ValueKind::Map => "map",
        ValueKind::Policy => "policy",
        ValueKind::Catalog => "catalog",
    }
}

fn relevance_name(value: RelevanceLevel) -> &'static str {
    match value {
        RelevanceLevel::Low => "low",
        RelevanceLevel::Medium => "medium",
        RelevanceLevel::High => "high",
    }
}

fn optimization_name(value: OptimizationClass) -> &'static str {
    match value {
        OptimizationClass::P1 => "p1",
        OptimizationClass::P2 => "p2",
        OptimizationClass::CStructured => "c_structured",
        OptimizationClass::CArtifact => "c_artifact",
        OptimizationClass::CComponent => "c_component",
        OptimizationClass::Pin => "pin",
    }
}

fn slot_name(value: CoreStrategySlot) -> &'static str {
    match value {
        CoreStrategySlot::Router => "iteron/router",
        CoreStrategySlot::Planner => "iteron/planner",
        CoreStrategySlot::Context => "iteron/context",
        CoreStrategySlot::Memory => "iteron/memory",
        CoreStrategySlot::Scheduler => "iteron/scheduler",
        CoreStrategySlot::ToolPolicy => "iteron/tool_policy",
        CoreStrategySlot::Verifier => "iteron/verifier",
        CoreStrategySlot::ModelRouter => "iteron/model_router",
        CoreStrategySlot::Collaboration => "iteron/collaboration",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask lives below the repository root")
            .to_path_buf()
    }

    #[test]
    fn generated_tunables_artifacts_do_not_drift() {
        check(&root()).expect(
            "tunables docs drifted; run `cargo run --locked -p iteron-xtask -- tunables generate`",
        );
    }

    #[test]
    fn human_projection_names_formal_schema_and_authority_boundary() {
        let rendered = render_markdown().unwrap();
        assert!(rendered.contains("**160** stable families"));
        assert!(rendered.contains("## Implementation status counts"));
        assert!(rendered.contains("`fixed_hidden`"));
        assert!(rendered.contains("`c_component`"));
        // The projection renders the JSON Schema type verbatim, and that type is `integer`, not
        // `numeric` -- see `docs/reference/tunables.md` row 67 for `provider_connect_tls_timeout`.
        // `tunables generate` reports no drift, so the generator and the committed doc agree and it
        // is this expectation that was stale.
        assert!(rendered.contains("integer [1..86400] seconds"));
        assert!(rendered.contains("## Authority boundary"));
        assert!(rendered.contains("`provider_connect_tls_timeout`"));
    }

    #[test]
    fn repository_source_locators_are_live() {
        validate_source_locators(&root()).unwrap();
    }
}
